---
- name: Get containers IP to variable containerIps
  shell: "lxc list {{ hostvars[item].inventory_hostname_short }} -c 4 | grep eth0 | awk '{ if ( $2 != \"\" ) print $2}'"
  register: containerIps
  with_items: 
    - "{{ groups['containers'] }}"

- name: Ensures all containers have a line in /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: ".*{{ hostvars[item.item].inventory_hostname_short }}.*"
    line: "{{ item.stdout }}\t{{ hostvars[item.item].inventory_hostname }} {{ hostvars[item.item].inventory_hostname_short }}" 
    state: present
  when: item.stdout != ""
  with_items:
    - "{{ containerIps.results }}"

